name: reports

on:
  workflow_dispatch:  # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make reports
        run: |
          python scripts/report.py

      - name: Make diagram
        run: |
          python scripts/diagram.py

      - name: Storing report artifacts
        uses: actions/upload-artifact@master
        with:
          name: reports
          path: scripts/resources

      - name: Commit Evolution CSV
        uses: EndBug/add-and-commit@v9
        with:
          add: 'scripts/resources/*evolution*.csv'

